ALTER TABLE meta.models
  ADD COLUMN score double precision NOT NULL DEFAULT 0.0;
ALTER TABLE meta.models ALTER COLUMN score DROP DEFAULT;

ALTER TABLE meta.models
  ADD COLUMN trained_ts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMESTAMP WITH TIME ZONE '1970-01-01 00:00:00+00';
ALTER TABLE meta.models ALTER COLUMN trained_ts DROP DEFAULT;
